import { useEffect, useState } from 'react'
import './advertising.css'

type AdMode = 'Disabled' | 'Sponsor' | 'AdSense'
type Ad = { enabled:boolean; mode:AdMode; label:string; text:string; targetUrl:string; imageUrl:string; adSenseClient:string; adSenseSlot:string }
const base=(import.meta.env.VITE_API_BASE_URL??'').replace(/\/$/,'')
async function api(path:string, options:RequestInit={}){const token=sessionStorage.getItem('milansetu_access_token');const r=await fetch(base+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message??'Request failed.');return d}
export default function SuperAdminAdvertisingPanel(){
 const [allowed,setAllowed]=useState(false),[ad,setAd]=useState<Ad>({enabled:false,mode:'Disabled',label:'Advertisement',text:'Help keep MilanSetu free for everyone.',targetUrl:'',imageUrl:'',adSenseClient:'',adSenseSlot:''}),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{void (async()=>{try{const me=await api('/api/auth/me');if(me.role!=='SuperAdmin')return;setAllowed(true);const d=await api('/api/advertising/admin');setAd({enabled:d.enabled,mode:d.mode??'Disabled',label:d.label??'Advertisement',text:d.text??'',targetUrl:d.targetUrl??'',imageUrl:d.imageUrl??'',adSenseClient:d.adSenseClient??'',adSenseSlot:d.adSenseSlot??''})}catch(e){setMessage(e instanceof Error?e.message:'Unable to load advertising settings.')}})()},[])
 if(!allowed)return null
 const save=async()=>{setBusy(true);setMessage('');try{await api('/api/advertising/admin',{method:'PUT',body:JSON.stringify(ad)});setMessage('Advertising settings saved.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save advertising settings.')}finally{setBusy(false)}}
 return <section className="admin-dashboard" aria-label="Super Admin advertising configuration"><div className="admin-dashboard-head"><div><p className="eyebrow">SUPER ADMIN</p><h2>Advertising</h2><p>Control the single minimal ad panel. MilanSetu remains free for users.</p></div></div><div style={{display:'grid',gap:12,maxWidth:700}}><label><input type="checkbox" checked={ad.enabled} onChange={e=>setAd({...ad,enabled:e.target.checked})}/> Enable advertising</label><label>Mode<select value={ad.mode} onChange={e=>setAd({...ad,mode:e.target.value as AdMode})}><option>Disabled</option><option>Sponsor</option><option>AdSense</option></select></label><label>Label<input value={ad.label} maxLength={80} onChange={e=>setAd({...ad,label:e.target.value})}/></label><label>Text<input value={ad.text} maxLength={500} onChange={e=>setAd({...ad,text:e.target.value})}/></label><label>Target URL<input type="url" value={ad.targetUrl} maxLength={1000} placeholder="https://…" onChange={e=>setAd({...ad,targetUrl:e.target.value})}/></label><label>Image URL<input type="url" value={ad.imageUrl} maxLength={1000} placeholder="https://…" onChange={e=>setAd({...ad,imageUrl:e.target.value})}/></label>{ad.mode==='AdSense'&&<><label>AdSense Client<input value={ad.adSenseClient} maxLength={200} placeholder="ca-pub-…" onChange={e=>setAd({...ad,adSenseClient:e.target.value})}/></label><label>AdSense Slot<input value={ad.adSenseSlot} maxLength={100} onChange={e=>setAd({...ad,adSenseSlot:e.target.value})}/></label></>}<button className="primary-button" type="button" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save advertising settings'}</button>{message&&<p role="status">{message}</p>}</div></section>
}
